version: '3.3'
services:
  shopify-app-ui:
    build: .
    ports:
    - "8081:8081"
    environment:
      NODE_ENV: production
      SHOPIFY_API_KEY: "YOUR_SHOPIFY_API_KEY"
      SHOPIFY_API_SECRET: "YOUR_SHOPIFY_SECRET"
      HOST: "http://example.com/"
      SCOPES: "write_products,write_customers,write_draft_orders,read_script_tags,write_script_tags"
      GLOBAL_ID_API_URL: "https://apps.globalid.dev/v1/shopify-plugin"
      ENCRYPTION_SECRET: "SECRET_TO_HMAC"
      GLOBAL_ID_DOMAIN: "https://api.globalid.dev"
      APP_CLIENT_ID: "blah"
      APP_CLIENT_SECRET: "secret_blah"
      BABEL_DISABLE_CACHE: "1"
