apiVersion: v1
kind: Service
metadata:
  name: {{ include "shopify-app-ui.fullname" . }}
  labels:
    app: {{ include "shopify-app-ui.name" . }}
    chart: {{ include "shopify-app-ui.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
  selector:
    app: {{ include "shopify-app-ui.name" . }}
    release: {{ .Release.Name }}
