export const GET_USER_INFO = 'GET_USER_INFO';
export const GET_USER_INFO_SUCCESS = 'GET_USER_INFO_SUCCESS';
export const GET_USER_INFO_FAILURE = 'GET_USER_INFO_FAILURE';

export const CHANGE_CONDITIONS = 'CHANGE_CONDITIONS';
export const CHANGE_CONDITIONS_SUCCESS = 'CHANGE_CONDITIONS_SUCCESS';
export const CHANGE_CONDITIONS_FAILURE = 'CHANGE_CONDITIONS_FAILURE';

export const SAVE_GLOBAL_STATE = 'SAVE_GLOBAL_STATE';
export const SAVE_GLOBAL_STATE_SUCCESS = 'SAVE_GLOBAL_STATE_SUCCESS';
export const SAVE_GLOBAL_STATE_FAILURE = 'SAVE_GLOBAL_STATE_FAILURE';

export const CHANGE_SHOP_NAME = 'CHANGE_SHOP_NAME';
export const CHANGE_AMOUNT = 'CHANGE_AMOUNT';

export const CHANGE_CLIENT_GLOBALID = 'CHANGE_CLIENT_GLOBALID';

export const GET_URL_SHOP = 'GET_URL_SHOP';
