replicaCount: "1"
annotations:
  iam.amazonaws.com/role: arn:aws:iam::715299534867:role/gid-dev-shopify-app-ui-api

globalidDomain:
  value: 'https://api.globalid.dev'

globalidApiUrl:
  value: 'https://apps.globalid.dev'
